Numpy
In NumPy, an array is the core data structure used to store and manipulate numerical data efficiently.
A NumPy array (called ndarray) is:

- A grid of values of the same data type

- Indexed by a tuple of nonnegative integers (like rows & columns for 2D arrays)

- Stored contiguously in memory, which makes it much faster than Python lists for numerical operations

Advantages Over Python Lists
- Faster computations (uses C under the hood)

- Vectorized operations (no need for loops)

- Supports multi-dimensional data (1D, 2D, 3D arrays)

- Rich mathematical functions (sum, mean, dot products, etc.)

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,5,7], dtype = int) #note: np array should store the same datatype
matrixB = np.array((2,3,5), dtype = float) #note:array can be installed as list, set etc.

In [3]:
print(a)

[1 2 3 5 7]


In [4]:
type(a)

numpy.ndarray

In [5]:
a.dtype

dtype('int64')

In [6]:
matrixB.dtype

dtype('float64')

Numpy(Dimensions)

In [7]:
# 1D Array (Vector)
arr1 = np.array([1, 2, 3, 4])
print(arr1)        

[1 2 3 4]


In [8]:
# 2D Array (Matrix)
arr2 = np.array([[1, 2, 3], [3, 4, 8]])
print(arr2)

[[1 2 3]
 [3 4 8]]


In [9]:
print(arr2.shape) # output: rows, columns
print(arr2.ndim) #basically how many rows (or 1D arrays inside)
print(arr2.dtype)
print(arr2.size) #total elements

(2, 3)
2
int64
6


In [10]:
arr2[1,2] # that means pick the array 2 and index 2 in arr2

np.int64(8)

In [11]:
arr3 = np.array([[1,2,5,4], [5,6,8,4]])
arr3.ndim


2

In [12]:
arr4 = np.array([[1,2,3], [2,4,5]]) #array can be multidimensional only if the arrays inside have the same number of elements

In [13]:
arr4.ndim

2

In [14]:
arr4[1,2]

np.int64(5)

In [15]:
arr5 = np.array([[1,2,3], [2,4,5], [-1,4,8]]) #since there are 3 rows but 1 column, so this is also 2 dim
arr5.ndim

2

In [16]:
arr6 = np.array([[[1, 2, 4], [3, 4, 8]],[[5, 6, 8], [7, 8, 9]]])# 2 rows and 2 columns, hence 3 dim
arr6.ndim

#Note: array of two 2 dim array is a 3 dim array
      #array of two 3 dim array is a 4 dim array

3

In [17]:
arr6[1,0,1]  

np.int64(6)

In [18]:
type(arr6)

numpy.ndarray

In [19]:
matrixA = np.array([2])
matrixA.ndim 

1

In [20]:
B = np.array(3)
B.ndim

0

Numpy (Shape)

In [21]:
arr6.shape #rows, columns, number of elements in each

(2, 2, 3)

In [22]:
arr6.shape[0] #in 3d array, number of 2 dimensional array

2

In [23]:
arr6.shape[1] #in each 2d array, number of 1d array

2

In [24]:
arr6.shape[2] #in each 1d array, number of elements

3

In [25]:
arr6.size #total number of elements

12

In [26]:
arr6.nbytes

96

Numpy (np.arange, reshape, random)

In [27]:
arr7 = np.arange(100) #arrange numbers till 100
print(arr7)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [28]:
arr7 = np.arange(20, 100, 3)
print(arr7) #arrange numbers from 20 till 100 skipping 2

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


NOTE: range() function doesn" create a list of numbers, it is used as an iterator in a loop
In order to create a list, it needs to be defined as print(list(range(0,10)))

In [29]:
print(range(0,10))

range(0, 10)


In [30]:
print(list(range(0,10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Random

In [31]:
arr8 = np.random.permutation(np.arange(10)) #creates a random shuffled list from 0 to 10
print(arr8)

[0 5 3 6 2 8 9 1 4 7]


In [32]:
v = np.random.randint(20, 300) #generates a random integer between the defined range

In [33]:
type(v)

int

In [34]:
matrixA = np.random.rand(10)

In [35]:
matrixA #the value of A can be any random value number until 10

array([0.75242438, 0.78973994, 0.33507014, 0.7073797 , 0.58137162,
       0.91588697, 0.85087246, 0.01470799, 0.65487362, 0.86190879])

In [36]:
C = np.random.rand(2,3) #generates a random 2d array

In [37]:
C

array([[0.75382806, 0.49964989, 0.36693898],
       [0.52602165, 0.26473254, 0.0387357 ]])

In [38]:
C.ndim

2

In [39]:
C = np.random.rand(2,3,4,2) #generates a random 4d array containing values from 1 to 10
C.ndim

4

In [40]:
C

array([[[[0.58149311, 0.03119456],
         [0.77973105, 0.67308256],
         [0.65432758, 0.16630104],
         [0.15433535, 0.19588349]],

        [[0.62620065, 0.88721771],
         [0.71267708, 0.41117269],
         [0.0066222 , 0.72459713],
         [0.65913731, 0.1876588 ]],

        [[0.2860056 , 0.6700325 ],
         [0.92791301, 0.56631422],
         [0.88267766, 0.65334855],
         [0.06655277, 0.22440501]]],


       [[[0.78543196, 0.5620145 ],
         [0.65896034, 0.05175869],
         [0.14021515, 0.56226224],
         [0.23491994, 0.33115279]],

        [[0.67370047, 0.22562522],
         [0.15869751, 0.35121372],
         [0.79070582, 0.28852211],
         [0.15745933, 0.24232854]],

        [[0.53413763, 0.21835623],
         [0.80493404, 0.13586249],
         [0.82347161, 0.28180207],
         [0.21133121, 0.18943686]]]])

In [41]:
D = np.arange(100).reshape(4,25)  #100 values are arranged in a (4,25) matrix

In [42]:
D.shape #shows the matrix shape(rows, columns)

(4, 25)

In [43]:
D = np.arange(100).reshape(4,5,5)
D.shape

(4, 5, 5)

Numpy (Slicing)

In [44]:
a[1:5] #index 1 till 5 but not 5
a[:5] #index 0 till 5 but not 5
a[:5] #index 0 till 5 but not 5
a[2:] #index 2 till end including last element
a[::-1] #from end till start (reverse the array)
a[::2] #from start till end every other element

array([1, 3, 7])

In [45]:
matrixA = np.arange(100)
matrixB = matrixA[3:10]
print(matrixB)

[3 4 5 6 7 8 9]


In [46]:
matrixB[0] = -1200

In [47]:
matrixB

array([-1200,     4,     5,     6,     7,     8,     9])

In [48]:
matrixA #the change is affected in both A and b, same memmory is accessed

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [49]:
matrixB = matrixA[3:10].copy() #this way the changes in b will not affect A anymore

In [50]:
matrixA[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [51]:
matrixA[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [52]:
matrixA[::-1]

array([   99,    98,    97,    96,    95,    94,    93,    92,    91,
          90,    89,    88,    87,    86,    85,    84,    83,    82,
          81,    80,    79,    78,    77,    76,    75,    74,    73,
          72,    71,    70,    69,    68,    67,    66,    65,    64,
          63,    62,    61,    60,    59,    58,    57,    56,    55,
          54,    53,    52,    51,    50,    49,    48,    47,    46,
          45,    44,    43,    42,    41,    40,    39,    38,    37,
          36,    35,    34,    33,    32,    31,    30,    29,    28,
          27,    26,    25,    24,    23,    22,    21,    20,    19,
          18,    17,    16,    15,    14,    13,    12,    11,    10,
           9,     8,     7,     6,     5,     4, -1200,     2,     1,
           0])

In [53]:
#find out the indice of the element in numpy array
elementIndex = np.argwhere(matrixA == -1200)[0][0] #index of the element -1200 will be returned

In [54]:
elementIndex

np.int64(3)

In [55]:
matrixA[elementIndex] = 3 #substiuting the element at that index with 3

In [56]:
matrixA

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [57]:
#np.random.rand  generates random values from 1 to 10
matrixA = np.round(10*np.random.rand(5, 4)) #matrix generated of 5 rows, 4 columns mulitplied by 10 and rounded off

In [58]:
matrixA #rows indices starting from 0,1,2 etc..
        #column indices starting from 0,1,2 etc.

array([[10.,  8.,  3., 10.],
       [ 8.,  1.,  9.,  5.],
       [ 4.,  1.,  9.,  4.],
       [ 8.,  6.,  1.,  3.],
       [ 6.,  5.,  8.,  7.]])

In [59]:
#row 1 has index 0, column 1 has index 0
#this means row 2, column 3
matrixA[1,2] 

np.float64(9.0)

In [60]:
matrixA[1, :] #to access the whole 2nd row

array([8., 1., 9., 5.])

In [61]:
matrixA[:, 1] #to access the whole 2nd column

array([8., 1., 1., 6., 5.])

In [62]:
matrixA[1:3, 2:4] #picks up rows from indices 1 to 3, not including 3 and columns with indices(2:4)

array([[9., 5.],
       [9., 4.]])

In [63]:
matrixA.T

array([[10.,  8.,  4.,  8.,  6.],
       [ 8.,  1.,  1.,  6.,  5.],
       [ 3.,  9.,  9.,  1.,  8.],
       [10.,  5.,  4.,  3.,  7.]])

In [64]:
import numpy.linalg as la

In [65]:
la.inv(np.random.rand(3,3))

array([[  1.14747528,  -2.24615676,   5.63104318],
       [  4.42816751,  -5.55881812,   8.82575029],
       [ -3.96267167,   6.9932704 , -11.60232104]])

In [66]:
matrixA.sort(axis=0) #sorting all columns individually
matrixA

array([[ 4.,  1.,  1.,  3.],
       [ 6.,  1.,  3.,  4.],
       [ 8.,  5.,  8.,  5.],
       [ 8.,  6.,  9.,  7.],
       [10.,  8.,  9., 10.]])

In [67]:
matrixA.sort(axis=1) #every row individually is sorted
matrixA


array([[ 1.,  1.,  3.,  4.],
       [ 1.,  3.,  4.,  6.],
       [ 5.,  5.,  8.,  8.],
       [ 6.,  7.,  8.,  9.],
       [ 8.,  9., 10., 10.]])

In [68]:
#Depending on the dimensionality of the array, axis = 0,1,2,..., the array can be sorted

Numpy(More Indexing)

In [69]:
matrixA = np.arange(100)
matrixB = matrixA[[3,5,6]] #copied 3th, 4th and 5th element from matrixA and added to matrixB
matrixB



array([3, 5, 6])

In [70]:
matrixB[0] = -4 #this change will happen only in matrixB not in matrixA
matrixB

#note: slicing will change both the parent matrix and the new matrix # matrixB = matrixA[3:10]

array([-4,  5,  6])

In [71]:
matrixA

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [72]:
matrixB = matrixA[(matrixA<40) & (matrixA>30)]
matrixB


array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [73]:
"""note: symbols used for arrays and true-false are different
        Arrays      True or False
           &           and
           |            or
           ~           not
"""

'note: symbols used for arrays and true-false are different\n        Arrays      True or False\n           &           and\n           |            or\n           ~           not\n'

Numpy(Broadcasting)

In [74]:
"""np.hstack
   np.vstack
   np.sort"""

'np.hstack\n   np.vstack\n   np.sort'

In [75]:
import numpy as np
matrixA = np.round(10*np.random.rand(2,3))
matrixA


array([[6., 7., 7.],
       [7., 5., 5.]])

In [76]:
matrixA+3

array([[ 9., 10., 10.],
       [10.,  8.,  8.]])

In [77]:
matrixA+(np.arange(2).reshape(2,1)) #every column of matrixA adds to the column of new generated matrix

array([[6., 7., 7.],
       [8., 6., 6.]])

In [78]:
matrixA

array([[6., 7., 7.],
       [7., 5., 5.]])

In [79]:
matrixB = np.round(10*np.random.rand(2,2))
matrixB


array([[7., 5.],
       [6., 6.]])

In [80]:
matrixC = np.hstack((matrixA, matrixB))
# to stack these matrices together, they are written as tuples inside the hstack function
matrixC

array([[6., 7., 7., 7., 5.],
       [7., 5., 5., 6., 6.]])

In [81]:
matrixD = np.random.permutation (np.arange(10))
matrixD

array([2, 1, 3, 4, 6, 5, 0, 8, 9, 7])

In [82]:
matrixD.sort() #sorted in ascending order
matrixD

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
np.sort(matrixD) #sorted in ascending order (another way)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
matrixD = matrixD[::-1] #sorted in descending order
matrixD

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [85]:
matrixE = np.array(["apple", "grapes", "banana", "mango"])

In [86]:
matrixE.sort() 
#note: strings can also be sorted in numpy as per the alphabetical order
matrixE

array(['apple', 'banana', 'grapes', 'mango'], dtype='<U6')

Numpy(Speed: ufuncs)

In [87]:
matrixF = np.random.rand(100000)
%timeit sum(matrixF)
%time np.sum(matrixF)  #Universal function is much faster

4.34 ms ± 202 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
CPU times: total: 0 ns
Wall time: 407 μs


np.float64(49960.899264324)

In [88]:
def mySum(G):
    sum = 0
    for x in G:
        sum += x
    return sum

In [89]:
%timeit mySum(matrixF)

5.41 ms ± 69.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
