Numpy
In NumPy, an array is the core data structure used to store and manipulate numerical data efficiently.
A NumPy array (called ndarray) is:

- A grid of values of the same data type

- Indexed by a tuple of nonnegative integers (like rows & columns for 2D arrays)

- Stored contiguously in memory, which makes it much faster than Python lists for numerical operations

Advantages Over Python Lists
- Faster computations (uses C under the hood)

- Vectorized operations (no need for loops)

- Supports multi-dimensional data (1D, 2D, 3D arrays)

- Rich mathematical functions (sum, mean, dot products, etc.)

In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3,5,7], dtype = int) #note: np array should store the same datatype
matrixB = np.array((2,3,5), dtype = float) #note:array can be installed as list, set etc.

In [3]:
print(a)

[1 2 3 5 7]


In [4]:
type(a)

numpy.ndarray

In [7]:
a.dtype

dtype('int64')

In [ ]:
matrixB.dtype

dtype('float64')

Numpy(Dimensions)

In [11]:
# 1D Array (Vector)
arr1 = np.array([1, 2, 3, 4])
print(arr1)        

[1 2 3 4]


In [14]:
# 2D Array (Matrix)
arr2 = np.array([[1, 2, 3], [3, 4, 8]])
print(arr2)

[[1 2 3]
 [3 4 8]]


In [ ]:
print(arr2.shape) # output: rows, columns
print(arr2.ndim) #basically how many rows (or 1D arrays inside)
print(arr2.dtype)
print(arr2.size) #total elements

(2, 3)
2
int64
6


In [ ]:
arr2[1,2] # that means pick the array 2 and index 2 in arr2

np.int64(8)

In [32]:
arr3 = np.array([[1,2,5,4], [5,6,8,4]])
arr3.ndim


2

In [29]:
arr4 = np.array([[1,2,3], [2,4,5]]) #array can be multidimensional only if the arrays inside have the same number of elements

In [39]:
arr4.ndim

2

In [40]:
arr4[1,2]

np.int64(5)

In [ ]:
arr5 = np.array([[1,2,3], [2,4,5], [-1,4,8]]) #since there are 3 rows but 1 column, so this is also 2 dim
arr5.ndim

2

In [53]:
arr6 = np.array([[[1, 2, 4], [3, 4, 8]],[[5, 6, 8], [7, 8, 9]]])# 2 rows and 2 columns, hence 3 dim
arr6.ndim

#Note: array of two 2 dim array is a 3 dim array
      #array of two 3 dim array is a 4 dim array

3

In [ ]:
arr6[1,0,1]  

np.int64(6)

In [49]:
type(arr6)

numpy.ndarray

In [ ]:
matrixA = np.array([2])
matrixA.ndim 

1

In [52]:
B = np.array(3)
B.ndim

0

Numpy (Shape)

In [ ]:
arr6.shape #rows, columns, number of elements in each

(2, 2, 3)

In [62]:
arr6.shape[0] #in 3d array, number of 2 dimensional array

2

In [63]:
arr6.shape[1] #in each 2d array, number of 1d array

2

In [64]:
arr6.shape[2] #in each 1d array, number of elements

3

In [66]:
arr6.size #total number of elements

12

In [67]:
arr6.nbytes

96

Numpy (np.arange, reshape, random)

In [ ]:
arr7 = np.arange(100) #arrange numbers till 100
print(arr7)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
arr7 = np.arange(20, 100, 3)
print(arr7) #arrange numbers from 20 till 100 skipping 2

[20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71 74 77 80 83 86 89
 92 95 98]


NOTE: range() function doesn" create a list of numbers, it is used as an iterator in a loop
In order to create a list, it needs to be defined as print(list(range(0,10)))

In [73]:
print(range(0,10))

range(0, 10)


In [74]:
print(list(range(0,10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


Random

In [ ]:
arr8 = np.random.permutation(np.arange(10)) #creates a random shuffled list from 0 to 10
print(arr8)

[5 4 9 6 1 2 8 3 0 7]


In [89]:
v = np.random.randint(20, 300) #generates a random integer between the defined range

In [90]:
type(v)

int

In [ ]:
matrixA = np.random.rand(10)

In [ ]:
matrixA #the value of A can be any random value number until 10

array([0.84656368, 0.71587237, 0.03818873, 0.45316292, 0.15510696,
       0.98110125, 0.5076189 , 0.16797304, 0.05335899, 0.88265953])

In [ ]:
C = np.random.rand(2,3) #generates a random 2d array

In [100]:
C

array([[0.53127778, 0.01222553, 0.61045612],
       [0.90848401, 0.44887756, 0.14146133]])

In [102]:
C.ndim

2

In [162]:
C = np.random.rand(2,3,4,2) #generates a random 4d array containing values from 1 to 10
C.ndim

4

In [161]:
C

array([[[[0.5157694 , 0.70460045],
         [0.70962462, 0.49846849],
         [0.41466609, 0.46779694],
         [0.31242392, 0.89533384]],

        [[0.95377272, 0.50629872],
         [0.63628032, 0.73672871],
         [0.04739615, 0.99096497],
         [0.65612771, 0.40404578]],

        [[0.38829602, 0.54165162],
         [0.52927511, 0.02543303],
         [0.29024633, 0.72220916],
         [0.4875089 , 0.36108722]]],


       [[[0.54319523, 0.10204529],
         [0.36755915, 0.18758804],
         [0.37947581, 0.79493898],
         [0.80736279, 0.90945094]],

        [[0.50825203, 0.14037717],
         [0.42136309, 0.29537235],
         [0.63607306, 0.02922278],
         [0.23475967, 0.94439326]],

        [[0.64696335, 0.63579118],
         [0.77886245, 0.29852111],
         [0.52714871, 0.1546415 ],
         [0.09541296, 0.15039314]]]])

In [ ]:
D = np.arange(100).reshape(4,25)  #100 values are arranged in a (4,25) matrix

In [107]:
D.shape #shows the matrix shape(rows, columns)

(4, 25)

In [109]:
D = np.arange(100).reshape(4,5,5)
D.shape

(4, 5, 5)

Numpy (Slicing)

In [124]:
a[1:5] #index 1 till 5 but not 5
a[:5] #index 0 till 5 but not 5
a[:5] #index 0 till 5 but not 5
a[2:] #index 2 till end including last element
a[::-1] #from end till start (reverse the array)
a[::2] #from start till end every other element

array([1, 3, 7])

In [ ]:
matrixA = np.arange(100)
matrixB = matrixA[3:10]
print(matrixB)

[3 4 5 6 7 8 9]


In [ ]:
matrixB[0] = -1200

In [ ]:
matrixB

array([-1200,     4,     5,     6,     7,     8,     9])

In [ ]:
matrixA #the change is affected in both A and b, same memmory is accessed

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [ ]:
matrixB = matrixA[3:10].copy() #this way the changes in b will not affect A anymore

In [ ]:
matrixA[::5]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
matrixA[::-5]

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [ ]:
matrixA[::-1]

array([   99,    98,    97,    96,    95,    94,    93,    92,    91,
          90,    89,    88,    87,    86,    85,    84,    83,    82,
          81,    80,    79,    78,    77,    76,    75,    74,    73,
          72,    71,    70,    69,    68,    67,    66,    65,    64,
          63,    62,    61,    60,    59,    58,    57,    56,    55,
          54,    53,    52,    51,    50,    49,    48,    47,    46,
          45,    44,    43,    42,    41,    40,    39,    38,    37,
          36,    35,    34,    33,    32,    31,    30,    29,    28,
          27,    26,    25,    24,    23,    22,    21,    20,    19,
          18,    17,    16,    15,    14,    13,    12,    11,    10,
           9,     8,     7,     6,     5,     4, -1200,     2,     1,
           0])

In [ ]:
#find out the indice of the element in numpy array
elementIndex = np.argwhere(matrixA == -1200)[0][0] #index of the element -1200 will be returned

In [148]:
elementIndex

np.int64(3)

In [ ]:
matrixA[elementIndex] = 3 #substiuting the element at that index with 3

In [ ]:
matrixA

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [179]:
#np.random.rand  generates random values from 1 to 10
matrixA = np.round(10*np.random.rand(5, 4)) #matrix generated of 5 rows, 4 columns mulitplied by 10 and rounded off

In [191]:
matrixA #rows indices starting from 0,1,2 etc..
        #column indices starting from 0,1,2 etc.

array([[ 9.,  1.,  3.,  6.],
       [ 6.,  2.,  4.,  0.],
       [10.,  2.,  6.,  1.],
       [ 4., 10.,  6.,  7.],
       [ 8.,  2.,  7.,  9.]])

In [181]:
#row 1 has index 0, column 1 has index 0
#this means row 2, column 3
matrixA[1,2] 

np.float64(4.0)

In [183]:
matrixA[1, :] #to access the whole 2nd row

array([6., 2., 4., 0.])

In [187]:
matrixA[:, 1] #to access the whole 2nd column

array([ 1.,  2.,  2., 10.,  2.])

In [190]:
matrixA[1:3, 2:4] #picks up rows from indices 1 to 3, not including 3 and columns with indices(2:4)

array([[4., 0.],
       [6., 1.]])

In [192]:
matrixA.T

array([[ 9.,  6., 10.,  4.,  8.],
       [ 1.,  2.,  2., 10.,  2.],
       [ 3.,  4.,  6.,  6.,  7.],
       [ 6.,  0.,  1.,  7.,  9.]])

In [193]:
import numpy.linalg as la

In [194]:
la.inv(np.random.rand(3,3))

array([[ -29.17592581,  -15.62814994,   33.32483284],
       [-314.73440787, -203.28200299,  390.81196812],
       [ 252.1472002 ,  160.97693789, -309.99872552]])

In [199]:
matrixA.sort(axis=0) #sorting all columns individually
matrixA

array([[ 4.,  1.,  3.,  0.],
       [ 6.,  2.,  4.,  1.],
       [ 8.,  2.,  6.,  6.],
       [ 9.,  2.,  6.,  7.],
       [10., 10.,  7.,  9.]])

In [205]:
matrixA.sort(axis=1) #every row individually is sorted
matrixA


array([[ 0.,  1.,  3.,  4.],
       [ 1.,  2.,  4.,  6.],
       [ 2.,  6.,  6.,  8.],
       [ 2.,  6.,  7.,  9.],
       [ 7.,  9., 10., 10.]])

In [206]:
#Depending on the dimensionality of the array, axis = 0,1,2,..., the array can be sorted

Numpy(More Indexing)

In [ ]:
matrixA = np.arange(100)
matrixB = matrixA[[3,5,6]] #copied 3th, 4th and 5th element from matrixA and added to matrixB
matrixB



array([3, 5, 6])

In [ ]:
matrixB[0] = -4 #this change will happen only in matrixB not in matrixA
matrixB

#note: slicing will change both the parent matrix and the new matrix # matrixB = matrixA[3:10]

array([-4,  5,  6])

In [216]:
matrixA

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [221]:
matrixB = matrixA[(matrixA<40) & (matrixA>30)]
matrixB


array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [223]:
"""note: symbols used for arrays and true-false are different
        Arrays      True or False
           &           and
           |            or
           ~           not
"""

'note: symbols used for arrays and true-false are different\n        Arrays      True or False\n           &           and\n           |            or\n           ~           not\n'

Numpy(Broadcasting)

In [ ]:
"""np.hstack
   np.vstack
   np.sort"""

In [3]:
import numpy as np
matrixA = np.round(10*np.random.rand(2,3))
matrixA


array([[ 9., 10.,  8.],
       [ 2.,  0.,  8.]])

In [4]:
matrixA+3

array([[12., 13., 11.],
       [ 5.,  3., 11.]])

In [6]:
matrixA+(np.arange(2).reshape(2,1)) #every column of matrixA adds to the column of new generated matrix

array([[ 9., 10.,  8.],
       [ 3.,  1.,  9.]])

In [7]:
matrixA

array([[ 9., 10.,  8.],
       [ 2.,  0.,  8.]])

In [9]:
matrixB = np.round(10*np.random.rand(2,2))
matrixB


array([[6., 4.],
       [2., 7.]])

In [ ]:
matrixC = np.hstack((matrixA, matrixB))
# to stack these matrices together, they are written as tuples inside the hstack function
matrixC

array([[ 9., 10.,  8.,  6.,  4.],
       [ 2.,  0.,  8.,  2.,  7.]])

In [34]:
matrixD = np.random.permutation (np.arange(10))
matrixD

array([3, 9, 7, 1, 6, 5, 8, 2, 4, 0])

In [ ]:
matrixD.sort() #sorted in ascending order
matrixD

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.sort(matrixD) #sorted in ascending order (another way)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
matrixD = matrixD[::-1] #sorted in descending order
matrixD

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
matrixE = np.array(["apple", "grapes", "banana", "mango"])

In [ ]:
matrixE.sort() 
#note: strings can also be sorted in numpy as per the alphabetical order
matrixE

array(['apple', 'banana', 'grapes', 'mango'], dtype='<U6')

Numpy(Speed: ufuncs)

In [ ]:
matrixF = np.random.rand(100000)
%timeit sum(matrixF)
%time np.sum(matrixF)  #Universal function is much faster

18.4 ms ± 2.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
CPU times: total: 0 ns
Wall time: 216 μs


np.float64(50020.486395195345)

In [45]:
def mySum(G):
    sum = 0
    for x in G:
        sum += x
    return sum

In [49]:
%timeit mySum(matrixF)

13.9 ms ± 352 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
