In [11]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())  # True if PyTorch can use GPU


2.8.0+cpu
False


Tensors (like NumPy arrays, but with GPU acceleration).

Example: Running physics simulations or mathematical optimization.

Creating an empty Tensor

In [17]:
x = torch.empty(2, 3) # Creates a 2x3 matrix with uninitialized values
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [24]:
x = torch.rand(2, 3, dtype=torch.float32) #float32 means 32-bit floating point 
print(x)
print(x.dtype)
print(x.size())  # 

tensor([[0.1128, 0.6813, 0.7987],
        [0.8011, 0.6627, 0.7073]])
torch.float32
torch.Size([2, 3])


In [29]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)
z = x + y
z = torch.add(x, y)  # another way to add
print(z)

y.add_(x)  # in-place addition
print(y)



tensor([[0.0567, 0.5290, 0.7510],
        [0.3881, 0.1367, 0.1421]])
tensor([[0.2775, 0.8939, 0.6649],
        [0.8018, 0.7095, 0.9365]])
tensor([[0.3342, 1.4230, 1.4159],
        [1.1898, 0.8463, 1.0787]])
tensor([[0.3342, 1.4230, 1.4159],
        [1.1898, 0.8463, 1.0787]])


In [31]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x - y
z = torch.sub(x, y)  # another way to subtract
print(z)

tensor([[0.6009, 0.5836, 0.2057],
        [0.7135, 0.7679, 0.7264]])
tensor([[0.5071, 0.5680, 0.3539],
        [0.8802, 0.8063, 0.4964]])
tensor([[ 0.0937,  0.0156, -0.1482],
        [-0.1667, -0.0383,  0.2300]])


In [34]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x * y
z = torch.mul(x, y)  # another way to multiply
print(z)

tensor([[0.3688, 0.5687, 0.7467],
        [0.8782, 0.7238, 0.3538]])
tensor([[0.9292, 0.2955, 0.1230],
        [0.8448, 0.0522, 0.9622]])
tensor([[0.3427, 0.1681, 0.0918],
        [0.7419, 0.0378, 0.3404]])


In [35]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x * y
z = torch.div(x, y)
print(z)

tensor([[0.8528, 0.3256, 0.2454],
        [0.9096, 0.4857, 0.7393]])
tensor([[0.9189, 0.2365, 0.5246],
        [0.7221, 0.4166, 0.3947]])
tensor([[0.9281, 1.3763, 0.4679],
        [1.2597, 1.1659, 1.8734]])


In [38]:
x = torch.rand(2, 3)

print(x)
print(x[:, 1])  # all rows, column 1
print(x[1, :])  # row 1, all columns
print(x[1, 1].item())  # get the value as a standard Python number


tensor([[0.5962, 0.4470, 0.9666],
        [0.4227, 0.6564, 0.9335]])
tensor([0.4470, 0.6564])
tensor([0.4227, 0.6564, 0.9335])
0.6563655734062195
