In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())  # True if PyTorch can use GPU


2.8.0+cpu
False


**What is PyTorch?**
- most popular research deep learning framework
- write fast deep learning code in Python (able to run on a GPU/many GPUs) 
- Able to access many pre-built deep learning models (Torch Hub/ torchdivisions.models)
- whole stack: preprocess data, model data, deploy model in your application/cloud
- originally designed and used in-house by Facebook/Meta (now open-source and used by companies such as Tesla, Microsoft, OpenAI)

**Tensors (like NumPy arrays, but with GPU acceleration).**

Example: Running physics simulations or mathematical optimization.

Creating an empty Tensor

In [2]:
x = torch.empty(2, 3) # Creates a 2x3 matrix with uninitialized values
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
x = torch.rand(2, 3, dtype=torch.float32) #float32 means 32-bit floating point 
print(x)
print(x.dtype)
print(x.size())  # 

tensor([[0.9869, 0.8820, 0.8432],
        [0.4471, 0.0795, 0.2123]])
torch.float32
torch.Size([2, 3])


In [4]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)
z = x + y
z = torch.add(x, y)  # another way to add
print(z)

y.add_(x)  # in-place addition
print(y)



tensor([[0.7523, 0.6466, 0.5609],
        [0.9690, 0.6739, 0.4421]])
tensor([[0.3866, 0.5990, 0.1351],
        [0.3345, 0.6026, 0.7544]])
tensor([[1.1389, 1.2456, 0.6960],
        [1.3035, 1.2766, 1.1965]])
tensor([[1.1389, 1.2456, 0.6960],
        [1.3035, 1.2766, 1.1965]])


In [5]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x - y
z = torch.sub(x, y)  # another way to subtract
print(z)

tensor([[0.0471, 0.0848, 0.9956],
        [0.5741, 0.3407, 0.0629]])
tensor([[0.8463, 0.0937, 0.5165],
        [0.0227, 0.4629, 0.2041]])
tensor([[-0.7992, -0.0089,  0.4790],
        [ 0.5514, -0.1222, -0.1412]])


In [6]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x * y
z = torch.mul(x, y)  # another way to multiply
print(z)

tensor([[0.8562, 0.1622, 0.8232],
        [0.5972, 0.9564, 0.0378]])
tensor([[0.1252, 0.1155, 0.2168],
        [0.1858, 0.3170, 0.1645]])
tensor([[0.1072, 0.0187, 0.1784],
        [0.1110, 0.3032, 0.0062]])


In [7]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x * y
z = torch.div(x, y)
print(z)

tensor([[0.1332, 0.2586, 0.2858],
        [0.4407, 0.1731, 0.9366]])
tensor([[0.1412, 0.1626, 0.7261],
        [0.5317, 0.7395, 0.7979]])
tensor([[0.9434, 1.5901, 0.3937],
        [0.8289, 0.2340, 1.1737]])


In [ ]:
x = torch.rand(2, 3)

print(x)
print(x[:, 1])  #all rows, column 1
print(x[1, :])  #row 1, all columns
print(x[1, 1].item())  #get the value as a standard Python number


tensor([[0.2736, 0.7368, 0.6594],
        [0.3983, 0.5495, 0.9184]])
tensor([0.7368, 0.5495])
tensor([0.3983, 0.5495, 0.9184])
0.5494594573974609
