In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import torch
print(torch.__version__)
print(torch.cuda.is_available())  # True if PyTorch can use GPU


2.8.0+cpu
False


**What is PyTorch?**
- most popular research deep learning framework
- write fast deep learning code in Python (able to run on a GPU/many GPUs) 
- Able to access many pre-built deep learning models (Torch Hub/ torchdivisions.models)
- whole stack: preprocess data, model data, deploy model in your application/cloud
- originally designed and used in-house by Facebook/Meta (now open-source and used by companies such as Tesla, Microsoft, OpenAI)

**Tensors (like NumPy arrays, but with GPU acceleration).**

Example: Running physics simulations or mathematical optimization.

Creating an empty Tensor

In [3]:
x = torch.empty(2, 3) # Creates a 2x3 matrix with uninitialized values
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
x = torch.rand(2, 3, dtype=torch.float32) #float32 means 32-bit floating point 
print(x)
print(x.dtype)
print(x.size())  # 

tensor([[0.5231, 0.0716, 0.0189],
        [0.6257, 0.4087, 0.4802]])
torch.float32
torch.Size([2, 3])


In [5]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)
z = x + y
z = torch.add(x, y)  # another way to add
print(z)

y.add_(x)  # in-place addition
print(y)



tensor([[0.8675, 0.1567, 0.5525],
        [0.4138, 0.3226, 0.4892]])
tensor([[0.8618, 0.9419, 0.6889],
        [0.4456, 0.3743, 0.6927]])
tensor([[1.7293, 1.0986, 1.2414],
        [0.8594, 0.6969, 1.1820]])
tensor([[1.7293, 1.0986, 1.2414],
        [0.8594, 0.6969, 1.1820]])


In [6]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x - y
z = torch.sub(x, y)  # another way to subtract
print(z)

tensor([[0.1195, 0.5168, 0.4708],
        [0.1073, 0.9763, 0.5229]])
tensor([[0.3829, 0.3972, 0.8682],
        [0.4477, 0.4965, 0.8410]])
tensor([[-0.2633,  0.1196, -0.3974],
        [-0.3405,  0.4798, -0.3182]])


In [7]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x * y
z = torch.mul(x, y)  # another way to multiply
print(z)

tensor([[0.0866, 0.4052, 0.2965],
        [0.9022, 0.7870, 0.3132]])
tensor([[3.3968e-01, 4.0245e-04, 2.6359e-01],
        [6.8650e-01, 1.3649e-01, 7.1906e-01]])
tensor([[2.9411e-02, 1.6306e-04, 7.8160e-02],
        [6.1935e-01, 1.0742e-01, 2.2518e-01]])


In [8]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x * y
z = torch.div(x, y)
print(z)

tensor([[0.9311, 0.2473, 0.6773],
        [0.4212, 0.4467, 0.0587]])
tensor([[0.0032, 0.6985, 0.3713],
        [0.4632, 0.5756, 0.2303]])
tensor([[2.9057e+02, 3.5403e-01, 1.8242e+00],
        [9.0924e-01, 7.7612e-01, 2.5481e-01]])


In [9]:
x = torch.rand(2, 3)

print(x)
print(x[:, 1])  #all rows, column 1
print(x[1, :])  #row 1, all columns
print(x[1, 1].item())  #get the value as a standard Python number


tensor([[0.1781, 0.9904, 0.6734],
        [0.2512, 0.8607, 0.2760]])
tensor([0.9904, 0.8607])
tensor([0.2512, 0.8607, 0.2760])
0.8606951832771301


In [10]:
#scalar tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [12]:
#get tensor back as a Python int
scalar.item()

7

In [13]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [15]:
vector.shape #2 elements in vector

torch.Size([2])

In [16]:
#Matrix
matrix = torch.tensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
matrix.ndim

2

In [18]:
matrix.shape #3 number of rows, 3 number of columns

torch.Size([3, 3])

In [19]:
#Tensor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9],
                        [10,11,12]],
                       [[19,20,21],
                        [22,23,24],
                        [25,26,27],
                        [28,29,30]]])
tensor   #most of the tensors we don't write by hand like this

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27],
         [28, 29, 30]]])

In [20]:
tensor.ndim #rows, columns and a layer, so total 3 dimensions

3

In [21]:
tensor.shape 
#2 layers and each matrix has 3 rows and 3 columns 
#therefore shape shows first the number of layers, then number of rows in the matrix and then the number of elements in each row

torch.Size([2, 4, 3])

**Random Tensors**

Random tensors are important because the way many neural networks learn is that they start with tensors full of random
numbers and then adjust those random numbers to better represent the data.

'Start with random numbers ==> look at data ==> update random numbers ==> look at data ==> update random numbers

In [22]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4) #creates a tensor of 3 rows and 4 columns with random values between 0 and 1
random_tensor

tensor([[0.4649, 0.0317, 0.6868, 0.0869],
        [0.4290, 0.7781, 0.0937, 0.4382],
        [0.5197, 0.9921, 0.1901, 0.2357]])

In [23]:
random_tensor.ndim

2

In [24]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.6315, 0.4093, 0.3088, 0.7538],
         [0.6091, 0.5497, 0.5183, 0.0867],
         [0.6829, 0.5301, 0.8629, 0.0866]]])

In [25]:
random_tensor.ndim

3

In [26]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) #color channels (RGB), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [27]:
#Create a tensor of all zeros
zeros = torch.zeros (size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
#Create a tensor of all ones
ones = torch.ones (size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

In [33]:
#create a range of tensors and tensors-like
one_to_ten = torch.arange(0, 10)  #similar to python's range function
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1 )
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
#creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)  #creates a tensor of zeros with the same shape as one_to_ten
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor Datatypes**

In [57]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                                     dtype = None, #what dtype is this tensor
                                     device = None, #what device is this tensor on
                                     requires_grad = False) #whether or not to track gradients with this tensor operations
float_32_tensor

                                     

tensor([3., 6., 9.])

**What is meant by 32-bit floatung point, 16-bit floating point and 64-bit floating point?**
- 32-bit is sigle precision (default)
- 16-bit is half precision
- These numbers represent how much detail a single numbers is stored in memory.

**NOTE:** Tensor datatypes is one of the 3 big errors you'll run with Pytorch and deep learning:
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

In [49]:
float_32_tensor.dtype  

torch.float32

In [55]:
#convert float32 tensor to float16 tensor (reduced precision, half precision)
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.long) #long means int64
int_32_tensor

tensor([3, 6, 9])

In [64]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

**Getting Information from Tensors (Tensors attributes)**
1. Tensors not right datatypes - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device- to get device from a tensor, can use tensor.device

In [65]:
##create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9911, 0.2969, 0.7358, 0.7270],
        [0.7771, 0.3672, 0.6128, 0.9605],
        [0.0455, 0.2575, 0.1600, 0.1793]])

In [68]:
some_tensor.size (), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [70]:
##find out the details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.9911, 0.2969, 0.7358, 0.7270],
        [0.7771, 0.3672, 0.6128, 0.9605],
        [0.0455, 0.2575, 0.1600, 0.1793]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu
