In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import torch
print(torch.__version__)
print(torch.cuda.is_available())  # True if PyTorch can use GPU


2.8.0+cpu
False


**What is PyTorch?**
- most popular research deep learning framework
- write fast deep learning code in Python (able to run on a GPU/many GPUs) 
- Able to access many pre-built deep learning models (Torch Hub/ torchdivisions.models)
- whole stack: preprocess data, model data, deploy model in your application/cloud
- originally designed and used in-house by Facebook/Meta (now open-source and used by companies such as Tesla, Microsoft, OpenAI)

**Tensors (like NumPy arrays, but with GPU acceleration).**

Example: Running physics simulations or mathematical optimization.

Creating an empty Tensor

In [10]:
x = torch.empty(2, 3) # Creates a 2x3 matrix with uninitialized values
print(x)

tensor([[1.0849, 1.4069, 1.1765],
        [0.6220, 0.8859, 1.3931]])


In [3]:
x = torch.rand(2, 3, dtype=torch.float32) #float32 means 32-bit floating point 
print(x)
print(x.dtype)
print(x.size())  # 

tensor([[0.6840, 0.1324, 0.0506],
        [0.2175, 0.4993, 0.7962]])
torch.float32
torch.Size([2, 3])


In [4]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)
z = x + y
z = torch.add(x, y)  # another way to add
print(z)

y.add_(x)  # in-place addition
print(y)



tensor([[0.3984, 0.5469, 0.7187],
        [0.1652, 0.5273, 0.4642]])
tensor([[0.6866, 0.8600, 0.4578],
        [0.4568, 0.3586, 0.9289]])
tensor([[1.0849, 1.4069, 1.1765],
        [0.6220, 0.8859, 1.3931]])
tensor([[1.0849, 1.4069, 1.1765],
        [0.6220, 0.8859, 1.3931]])


In [11]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x - y
z = torch.sub(x, y)  # another way to subtract
print(z)

tensor([[0.6635, 0.7120, 0.8470],
        [0.4327, 0.2707, 0.8365]])
tensor([[0.9628, 0.4074, 0.0365],
        [0.9961, 0.0649, 0.8109]])
tensor([[-0.2993,  0.3046,  0.8105],
        [-0.5634,  0.2057,  0.0256]])


In [6]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x * y
z = torch.mul(x, y)  # another way to multiply
print(z)

tensor([[0.4901, 0.0024, 0.7160],
        [0.5371, 0.3123, 0.5684]])
tensor([[0.5255, 0.2044, 0.2235],
        [0.9770, 0.7815, 0.3577]])
tensor([[2.5759e-01, 4.9420e-04, 1.5999e-01],
        [5.2478e-01, 2.4404e-01, 2.0334e-01]])


In [7]:
x = torch.rand(2, 3)
y = torch.rand(2, 3)
print(x)
print(y)

z = x * y
z = torch.div(x, y)
print(z)

tensor([[0.6719, 0.0887, 0.7173],
        [0.7514, 0.9246, 0.8203]])
tensor([[0.0728, 0.5485, 0.2375],
        [0.4613, 0.6144, 0.8779]])
tensor([[9.2289, 0.1617, 3.0200],
        [1.6288, 1.5047, 0.9344]])


In [15]:
x = torch.rand(2, 3)

print(x)
print(x[:, 1])  #all rows, column 1
print(x[1, :])  #row 1, all columns
print(x[1, 1].item())  #get the value as a standard Python number


tensor([[0.5616, 0.4107, 0.5351],
        [0.9307, 0.1305, 0.4082]])
tensor([0.4107, 0.1305])
tensor([0.9307, 0.1305, 0.4082])
0.13045114278793335


In [21]:
#scalar tensors
scalar = torch.tensor(7)
scalar

tensor(7)

In [22]:
scalar.ndim

0

In [24]:
#get tensor back as a Python int
scalar.item()

7

In [34]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [35]:
vector.ndim

1

In [ ]:
vector.shape #2 elements in vector

torch.Size([2])

In [36]:
#Matrix
matrix = torch.tensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [33]:
matrix.ndim

2

In [39]:
matrix.shape #3 number of rows, 3 number of columns

torch.Size([3, 3])

In [57]:
#Tensor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9],
                        [10,11,12]],
                       [[19,20,21],
                        [22,23,24],
                        [25,26,27],
                        [28,29,30]]])
tensor   #most of the tensors we don't write by hand like this

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27],
         [28, 29, 30]]])

In [61]:
tensor.ndim #rows, columns and a layer, so total 3 dimensions

3

In [60]:
tensor.shape 
#2 layers and each matrix has 3 rows and 3 columns 
#therefore shape shows first the number of layers, then number of rows in the matrix and then the number of elements in each row

torch.Size([2, 4, 3])

**Random Tensors**

Random tensors are important because the way many neural networks learn is that they start with tensors full of random
numbers and then adjust those random numbers to better represent the data.

'Start with random numbers ==> look at data ==> update random numbers ==> look at data ==> update random numbers

In [70]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4) #creates a tensor of 3 rows and 4 columns with random values between 0 and 1
random_tensor

tensor([[0.4278, 0.7798, 0.9465, 0.0228],
        [0.3486, 0.6633, 0.5897, 0.6574],
        [0.4924, 0.0643, 0.1522, 0.4294]])

In [69]:
random_tensor.ndim

3

In [72]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.4671, 0.1596, 0.3458, 0.3582],
         [0.4742, 0.2635, 0.1437, 0.5431],
         [0.2878, 0.3117, 0.3649, 0.6399]]])

In [73]:
random_tensor.ndim

3

In [78]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) #color channels (RGB), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
#Create a tensor of all zeros
zeros = torch.zeros (size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [84]:
#Create a tensor of all ones
ones = torch.ones (size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [85]:
ones.dtype

torch.float32